/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cprm.gov.gileno.macedo.VISAO;

import cprm.gov.gileno.macedo.MODELO.Sessao;
import java.awt.Desktop;
import java.awt.Frame;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.Serializable;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JRException;

/**
 *
 * @author gileno.macedo
 */
public class TelaPrincipal extends javax.swing.JFrame implements Serializable {

    public TelaPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
        this.setTitle("ArcMapa (Mapoteca Sureg_MA)");
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jP_menu = new javax.swing.JPanel();
        menuCadMapas = new javax.swing.JLabel();
        menuPesquisas = new javax.swing.JLabel();
        menuRelatorios = new javax.swing.JLabel();
        menuAjuda = new javax.swing.JLabel();
        minimizar = new javax.swing.JLabel();
        sair = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(140, 123, 117));

        jP_menu.setBackground(new java.awt.Color(82, 60, 60));

        menuCadMapas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-cadastrar 64.png"))); // NOI18N
        menuCadMapas.setToolTipText("Cadastros");
        menuCadMapas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuCadMapas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuCadMapasMouseClicked(evt);
            }
        });

        menuPesquisas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuPesquisas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-Search-64.png"))); // NOI18N
        menuPesquisas.setToolTipText("Pesquisas");
        menuPesquisas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuPesquisas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuPesquisasMouseClicked(evt);
            }
        });

        menuRelatorios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuRelatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-Download Graph Report-64.png"))); // NOI18N
        menuRelatorios.setToolTipText("Relatórios");
        menuRelatorios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuRelatorios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuRelatoriosMouseClicked(evt);
            }
        });

        menuAjuda.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuAjuda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuAjuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-Settings-64.png"))); // NOI18N
        menuAjuda.setToolTipText("Ajuda");
        menuAjuda.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        menuAjuda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuAjuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuAjudaMouseClicked(evt);
            }
        });

        minimizar.setBackground(new java.awt.Color(188, 170, 164));
        minimizar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        minimizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-Minimize Window-32 (1).png"))); // NOI18N
        minimizar.setToolTipText("Minimizar");
        minimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizarMouseClicked(evt);
            }
        });

        sair.setBackground(new java.awt.Color(188, 170, 164));
        sair.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sair.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-Close Window-32.png"))); // NOI18N
        sair.setToolTipText("Sair");
        sair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sairMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jP_menuLayout = new javax.swing.GroupLayout(jP_menu);
        jP_menu.setLayout(jP_menuLayout);
        jP_menuLayout.setHorizontalGroup(
            jP_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_menuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menuCadMapas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuPesquisas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuRelatorios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(menuAjuda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(minimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(sair, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jP_menuLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {menuAjuda, menuCadMapas, menuPesquisas, menuRelatorios});

        jP_menuLayout.setVerticalGroup(
            jP_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_menuLayout.createSequentialGroup()
                .addGroup(jP_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sair)
                    .addComponent(minimizar))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_menuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jP_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(menuPesquisas, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menuRelatorios)
                    .addComponent(menuAjuda)
                    .addComponent(menuCadMapas, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jP_menuLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {menuAjuda, menuPesquisas, menuRelatorios});

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/mapMapa_1.JPG"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jP_menu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(42, 42, 42))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jP_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 733, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuCadMapasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCadMapasMouseClicked
        try {
            MenuCad menuCadastros = new MenuCad();
            menuCadastros.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuCadMapasMouseClicked

    private void menuPesquisasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuPesquisasMouseClicked
        try {
            MenuPesquisas menuPesqu = new MenuPesquisas();
            menuPesqu.setVisible(true);
            Thread.sleep(300);
            this.setState(Frame.ICONIFIED);
        } catch (Exception ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuPesquisasMouseClicked

    private void menuRelatoriosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuRelatoriosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_menuRelatoriosMouseClicked

    private void menuAjudaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuAjudaMouseClicked
       lerPDF();
    }//GEN-LAST:event_menuAjudaMouseClicked

    private void minimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizarMouseClicked
        try {
            Thread.sleep (300);
            this.setState(Frame.ICONIFIED);
        } catch (InterruptedException ex) {
            Logger.getLogger(LoginUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_minimizarMouseClicked

    private void sairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sairMouseClicked
        try {
            Thread.sleep (300);
            this.dispose();
        } catch (InterruptedException ex) {
            Logger.getLogger(LoginUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_sairMouseClicked
     private void lerPDF(){
      if (Desktop.isDesktopSupported()) {
            // Arquivo no diretório de trabalho do usuário, System.getProperty ("user.dir");
            File file = new File("Tutorialcadastro.pdf");
            if (!file.exists()) {
                // no JAR
                InputStream inputStream = ClassLoader.getSystemClassLoader()
                        .getResourceAsStream("Tutorial/Tutorialcadastro.pdf");
                // copiando arquivo
                OutputStream outputStream = null;
                try {
                    outputStream = new FileOutputStream(file);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
                byte[] buffer = new byte[1024];
                int length;
                try {
                    while ((length = inputStream.read(buffer)) > 0) {
                        outputStream.write(buffer, 0, length);
                    }
                } catch (IOException ex) {
                    Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    outputStream.close();
                } catch (IOException ex) {
                    Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    inputStream.close();
                } catch (IOException ex) {
                    Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            try {
                // Open file
                Desktop.getDesktop().open(file);
            } catch (IOException ex) {
                Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
     
     }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jP_menu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel menuAjuda;
    private javax.swing.JLabel menuCadMapas;
    private javax.swing.JLabel menuPesquisas;
    private javax.swing.JLabel menuRelatorios;
    private javax.swing.JLabel minimizar;
    private javax.swing.JLabel sair;
    // End of variables declaration//GEN-END:variables
}
